name: update
on: 
  push: 
    branches: [ "master" ]

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Publish update
        run: eas update --auto
      
      # - name: Build andorid
      #   run: eas build --platform android --profile androidapk --non-interactive

      - name: Download and push new apk
        run: |
          sudo apt-get update
          sudo apt-get install jq
          sudo apt-get install wget
          sudo apt-get install curl
          OUTPUT=$(eas build:list --json --limit=1 --non-interactive | jq -r '.[0].artifacts.buildUrl')
          VERSION=$(curl https://raw.githubusercontent.com/rajasekhar1404/react-native/master/package.json | jq -r '.version')
          wget -O krs_$VERSION.apk $OUTPUT
          git clone https://${{ secrets.TOKEN }}@github.com/rajasekhar1404/krs-mobile-builds
          cd krs-mobile-builds
          mv -f ../krs_$VERSION.apk .
          git add .
          git config --global user.email "rajasekhar@gmail.com"
          git config --global user.name "rajasekhar"
          git commit -m "updated to latest"
          git push -u origin main